name: stripe_example
description: Demonstrates how to use the stripe plugin.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=2.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_stripe: ^2.4.0
  functions_dart:
    path: ../../functions-dart
  http: ^0.13.1
  stripe_checkout: ^0.1.2
  supabase: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.8.2

flutter:
  uses-material-design: true

  assets:
    - assets/
  fonts:
    - family: OtomanopeeOne
      fonts:
        - asset: fonts/OtomanopeeOne.ttf
