name: stripe_example
description: Demonstrates how to use the Supabase functions to complete Stripe checkout
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=2.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_stripe: ^2.4.0
  # functions_client: ^0.0.1-dev.1
  # supabase: ^0.3.0
  supabase:
    path: ../../supabase-dart

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.8.2

flutter:
  uses-material-design: true
